export enum QueryKeys {
  PROVINCE = "province",
  DISTRICT = "district",
  WARD = "ward",
  REGISTER = "register",
  LOGIN = "login",
  SEAT_TYPE = "seat-type",
  CREATE_CINEMA = "create-cinema",
  GET_CINEMA = "get-cinema",
  GET_CINEMA_DETAIL = "get-cinema-detail",
  UPDATE_CINEMA = "update-cinema",
  CREATE_FACILITY = "create-facility",
  GET_FACILITY_BY_CINEMA_ID = "get-facility-by-cinema-id",
  GET_FACILITY = "get-facility",
  GET_FACILITY_DETAIL = "get-facility-detail",
  VERIFIED = "Verified",
  USER_INFO = "user-info",
  CREATE_HALL = "create-hall",
  GET_HALL_DETAIL = "get-hall-detail",
  GET_HALL_ALL = "get-hall-all",
}
